---
version: 2.1
jobs:
  build:
    working_directory: ~/sqns
    docker:
      - image: circleci/elixir:1.9
        environment:
          MIX_ENV: test
      - image: nulib/goaws
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "mix.lock" }}
      - run:
          name: Install hex & rebar
          command: mix do local.hex --force, local.rebar --force
      - run:
          name: Install Elixir Dependencies
          command: mix do deps.get, deps.compile
      - save_cache:
          key: dependency-cache-{{ checksum "mix.lock" }}
          paths:
            - ~/sqns/deps
            - ~/sqns/_build
      - run:
          name: Elixir Static Analysis
          command: mix credo
      - run:
          name: Elixir Tests
          command: mix test && (mix coveralls.circle || true)
      - store_artifacts:
          path: /tmp/test-results
          destination: tests
