---
version: 2
jobs:
  build:
    working_directory: ~/sqns
    docker:
      - image: circleci/elixir:1.9
        environment:
          MIX_ENV: test
      - image: nulib/goaws
    steps:
      - checkout
      - run:
          name: Install hex & rebar
          command: mix do local.hex --force, local.rebar --force
      - run:
          name: Install Elixir Dependencies
          command: mix do deps.get, deps.compile
      - run:
          name: Elixir Static Analysis
          command: mix credo
      - run:
          name: Elixir Tests
          command: mix test
